CUDA_VISIBLE_DEVICES="0" python train.py --task dmc_walker_run --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="1" python train.py --task dmc_cheetah_run --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="2" python train.py --task dmc_hopper_hop --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="3" python train.py --task metaworld_dial_turn --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="4" python train.py --task metaworld_reach --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="5" python train.py --task metaworld_lever_pull --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="6" python train.py --task metaworld_door_lock --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1

# test
CUDA_VISIBLE_DEVICES="3" python test.py --task metaworld_dial_turn --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 10 --work_dir /data1/qiuzh/wansh/RL/experiments/drq/runs/metaworld_dial_turn/20250615-015050_seed1