# DIAYN

CUDA_VISIBLE_DEVICES="0" python train.py --task dmc_walker_run --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="1" python train.py --task dmc_cheetah_run --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="2" python train.py --task dmc_hopper_hop --num_skills 10 --num_train_steps 1000000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 1000 --action_repeat 2 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="3" python train.py --task metaworld_dial_turn --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="4" python train.py --task metaworld_reach --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="5" python train.py --task metaworld_lever_pull --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1
CUDA_VISIBLE_DEVICES="6" python train.py --task metaworld_door_lock --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --save_video True --log_save_tb True --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 1

# test
CUDA_VISIBLE_DEVICES="3" python test.py --task metaworld_dial_turn --num_skills 10 --num_train_steps 500000 --encoder_feature_dim 50 --lr 3e-4 --lr_discriminator 3e-4 --time_limit 500 --action_repeat 1 --framestack 3 --num_eval_episodes 10 --work_dir /data1/qiuzh/wansh/RL/experiments/drq/runs/metaworld_dial_turn/20250615-015050_seed1

# METRA

MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=1 python train_metra.py --task metaworld_reach --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 1000 --n_epochs_per_pt_save 1000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=3 python train_metra.py --task metaworld_dial_turn --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 1000 --n_epochs_per_pt_save 1000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=3 python train_metra.py --task metaworld_drawer_close --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 5000 --n_epochs_per_pt_save 5000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=2 python train_metra.py --task metaworld_door_open --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 5000 --n_epochs_per_pt_save 5000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=7 python train_metra.py --task metaworld_lever_pull --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 5000 --n_epochs_per_pt_save 5000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=2 python train_metra.py --task metaworld_button_press_topdown_wall --time_limit 250 --seed 0 --traj_batch_size 4 --video_skip_frames 2 --num_video_repeats 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 100000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 100 --n_epochs_per_log 10 --n_epochs_per_eval 500 --n_epochs_per_save 5000 --n_epochs_per_pt_save 5000 --discrete 1 --dim_skill 8 --encoder 1 --sample_cpu 0 --action_repeat 1 --n_epochs 5000

MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=7 python train_metra.py --task dmc_quadruped_run --time_limit 200 --seed 0 --traj_batch_size 8 --normalizer_type off --video_skip_frames 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 300000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 200 --n_epochs_per_log 25 --n_epochs_per_eval 125 --n_epochs_per_save 1000 --n_epochs_per_pt_save 1000 --discrete 0 --dim_skill 4 --encoder 1 --sample_cpu 0 --action_repeat 2 --n_epochs 10000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=7 python train_metra.py --task dmc_cheetah_run --time_limit 200 --seed 0 --traj_batch_size 8 --normalizer_type off --video_skip_frames 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 300000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 200 --n_epochs_per_log 25 --n_epochs_per_eval 250 --n_epochs_per_save 1000 --n_epochs_per_pt_save 1000 --discrete 0 --dim_skill 4 --encoder 1 --sample_cpu 0 --action_repeat 2 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=3 python train_metra.py --task dmc_walker_run --time_limit 200 --seed 0 --traj_batch_size 8 --normalizer_type off --video_skip_frames 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 300000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 200 --n_epochs_per_log 25 --n_epochs_per_eval 250 --n_epochs_per_save 1000 --n_epochs_per_pt_save 1000 --discrete 0 --dim_skill 4 --encoder 1 --sample_cpu 0 --action_repeat 2 --n_epochs 5000
MUJOCO_GL=egl CUDA_VISIBLE_DEVICES=2 python train_metra.py --task dmc_hopper_hop --time_limit 200 --seed 0 --traj_batch_size 8 --normalizer_type off --video_skip_frames 2 --framestack 3 --sac_min_buffer_size 10000 --sac_max_buffer_size 300000 --eval_plot_axis -15 15 -15 15 --algo metra --trans_optimization_epochs 200 --n_epochs_per_log 25 --n_epochs_per_eval 250 --n_epochs_per_save 5000 --n_epochs_per_pt_save 5000 --discrete 0 --dim_skill 4 --encoder 1 --sample_cpu 0 --action_repeat 2 --n_epochs 5000